// import type { Metadata } from "react-head";
//import { Providers } from "./providers";
import NavBar from "./components/Navbar/Navbar";

import "./globals.css";

/* export const metadata: Metadata = {
  title: "Swerve VOD Management System",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className='main-layout'>
        <NavBar />

        <div className='content'>
            {children}
        </div>
        
    </div>
  );
}
